/**
 * Server Side Rendering
 */
import { APIGatewayEvent } from 'aws-lambda';
import * as React from 'react';
import { renderToString } from 'react-dom/server';

import App           from '../App.js';
import ConfigContext from '../components/ConfigContext.js';
import config        from './config.js';
import html          from './html.js';
import { Stats }     from './types.js';

export type Type_render_args = APIGatewayEvent;
export type Type_render_ret  = Promise<string>;

/**
 * Server-side rendering
 */
export default async function render( event: Type_render_args ): Type_render_ret { // eslint-disable-line @typescript-eslint/no-unused-vars
	// The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
	// TODO: May need to be dist/webpack
	const stats = (await import( '../../webpack/stats.json' ) ).default as unknown as Stats; // ts-eslint does not like variables as an import argument
	//const stats = (await import( '../../stats.json' ) ).default as unknown as Stats; // ts-eslint does not like variables as an import argument
	//console.log( "Stats: ", { t: typeof stats, str: JSON.stringify(stats) } );
	const content = renderToString(
		<ConfigContext.Provider value={config}>
			<App/>
		</ConfigContext.Provider>,
	);
	//console.log('render: rendered content: [', content, ']');
	return html({ stats, content, config });
}
