/**
 * File:        server/render.tsx
 * Description: Server-side rendering for the application.
 */

////////////////////////////////////////////////////////////////////////////////
// Imports

import { APIGatewayEvent } from 'aws-lambda';
import * as React from 'react';
import { renderToString } from 'react-dom/server';

import App           from '#App';
import ConfigContext from '#components/ConfigContext';
import config        from '#server/config';
import html          from '#server/html';
import { Stats }     from '#server/types';

////////////////////////////////////////////////////////////////////////////////
// Types

////////////////////////////////////////
// Imported types

////////////////////////////////////////
// Exported and local types

export type Type_render_args = APIGatewayEvent;
export type Type_render_ret  = Promise<string>;

////////////////////////////////////////////////////////////////////////////////
// Constants

////////////////////////////////////////////////////////////////////////////////
// Definitions

////////////////////////////////////////
// Local definitions

////////////////////////////////////////
// Exported definitions

/**
 * @description Server-side rendering of a HTML page.
 * @param event : API Gateway event.
 */
export default async function render( event: Type_render_args ): Type_render_ret { // eslint-disable-line @typescript-eslint/no-unused-vars
	// The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
	//const stats = (await import( '../../dist/webpack/stats.json' ) ).default as unknown as Stats;
	const stats = (await import( '../../dist/stats.json' ) ).default as unknown as Stats;
	// Use the following dummy definition if needed
	//const stats = {
	//	scripts: [],
	//	styles:  [],
	//};
	//console.log( "Stats: ", { t: typeof stats, str: JSON.stringify(stats), config: JSON.stringify(config) } );
	const content = renderToString(
		<ConfigContext.Provider value={config}>
			<App/>
		</ConfigContext.Provider>,
	);
	//console.log('render: rendered content: [', content, ']');
	return html({ stats, content, config });
}

////////////////////////////////////////////////////////////////////////////////
// Unit test definitions
