import '../public/gip-common.css';

import * as React    from 'react';

//import useConfig     from './components/useConfig';
import GipEdit       from './components/gip_edit.js';
//import { Amplify } from 'aws-amplify';
//import { Authenticator } from '@aws-amplify/ui-react';
//import awsExports from './aws-exports'; // Generated by Amplify CLI
//import 'bootstrap/dist/css/bootstrap.min.css';

//Amplify.configure(awsExports);

/**
 * Our Web Application
 */
export default function App() : React.JSX.Element {
	//const config = useConfig();
	return (
		<GipEdit />
	);
	//<Authenticator>
	//  <GipEdit />
	//</Authenticator>
}
